version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска бота администрирования Discord серверами + веб-интерфейса для его управлением.
  yagpdb:
    command: ["-all", "-pa", "-exthttps=true", "-https=false"]
    container_name: yagpdb
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: yagpdb.env
    image: teyker/yagpdb:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.yagpdb.entrypoints: "websecure"
      traefik.http.routers.yagpdb.rule: "Host(`yagpdb.${DOMAIN}`)"
      traefik.http.routers.yagpdb.service: "yagpdb"
      traefik.http.routers.yagpdb.tls.certresolver: "letsencrypt"
      traefik.http.services.yagpdb.loadbalancer.server.port: "80"
    volumes:
      - "./src/cert:/app/cert"
      - "./src/soundboard:/app/soundboard"

networks:
  default:
    external: true
    name: $NETWORK
