version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска бота администрирования Discord серверами + веб-интерфейса для его управлением.
  discord-yagpdb:
    command: ["-all", "-pa", "-exthttps=true", "-https=false"]
    container_name: discord-yagpdb
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: yagpdb.env
    image: teyker/yagpdb:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.discord-yagpdb.entrypoints: "websecure"
      traefik.http.routers.discord-yagpdb.rule: "Host(`discord.${DOMAIN}`)"
      traefik.http.routers.discord-yagpdb.service: "discord-yagpdb"
      traefik.http.routers.discord-yagpdb.tls.certresolver: "letsencrypt"
      traefik.http.services.discord-yagpdb.loadbalancer.server.port: "80"
    volumes:
      - "./yagpdb/cert:/app/cert"
      - "./yagpdb/soundboard:/app/soundboard"

networks:
  external:
    external: true
    name: $NETWORK
